import Head from "next/head";
import { Button, FileUpload, Flex, Stack, Text } from "@chakra-ui/react";
import { HiUpload } from "react-icons/hi";
import { useState } from "react";

export default function Home() {
  const [, setFile] = useState<File | null>(null);

  const handleFileChange = async (details: { acceptedFiles: File[] }) => {
    const file = details.acceptedFiles[0] || null;
    console.log(file);
    setFile(file);

    if (file) {
      try {
        const formData = new FormData();
        formData.append("file", file);

        const response = await fetch("/api/markle-tree", {
          method: "POST",
          body: formData,
        });

        const result = await response.json();
        console.log("API Response:", result);
      } catch (error) {
        console.error("Error uploading file:", error);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack>
        <Text>Upload CSV</Text>
        <Flex>
          <FileUpload.Root onFileChange={handleFileChange}>
            <FileUpload.HiddenInput />
            <FileUpload.Trigger asChild>
              <Button variant="outline" size="sm">
                <HiUpload /> Upload file
              </Button>
            </FileUpload.Trigger>
            <FileUpload.List />
          </FileUpload.Root>
        </Flex>
      </Stack>
    </>
  );
}
